"use client";

export default function HowSolaceWorks() {
  return (
    <div className="space-y-12 text-slate-200">
      {/* SECTION 1 */}
      <section>
        <h3 className="mb-2 text-lg font-semibold text-slate-100">
          1. Curated, Not Crawled
        </h3>
        <p className="text-sm text-slate-400">
          Solace does not browse the open web. She reads a verified, curated
          digest generated by Moral Clarity AI’s media engine — designed to
          eliminate real-time manipulation, prompt poisoning, and incentive
          gaming.
        </p>
      </section>

      {/* SECTION 2 */}
      <section>
        <h3 className="mb-2 text-lg font-semibold text-slate-100">
          2. Bias Is Measured, Not Claimed
        </h3>
        <p className="text-sm text-slate-400">
          Every story is scored for bias intent, framing pressure, omission
          patterns, and narrative predictability. These scores are mathematical,
          reproducible, and tracked longitudinally across outlets.
        </p>
      </section>

      {/* SECTION 3 */}
      <section>
        <h3 className="mb-2 text-lg font-semibold text-slate-100">
          3. Ledger-Locked Outputs
        </h3>
        <p className="text-sm text-slate-400">
          Once scored, each digest entry is cryptographically locked into MCAI’s
          ledger. Solace reads from this ledger — not mutable feeds — ensuring
          stability, auditability, and temporal consistency.
        </p>
      </section>

      {/* SECTION 4 */}
      <section>
        <h3 className="mb-2 text-lg font-semibold text-slate-100">
          4. Neutral Delivery
        </h3>
        <p className="text-sm text-slate-400">
          Solace’s delivery layer is constrained by neutrality rules. She does
          not persuade, amplify, or editorialize. Her role is to present
          information — not influence belief.
        </p>
      </section>
    </div>
  );
}
