// app/edge-of-knowledge/hodge-conjecture-algebraicity-obstruction/page.tsx

import type { Metadata } from "next";

export const metadata: Metadata = {
  title:
    "The Hodge Conjecture: Algebraicity as a Completeness Boundary | Edge of Knowledge",
  description:
    "A formal epistemic boundary showing that current approaches assume algebraic completeness without proof, limiting claim authority.",
  robots: {
    index: true,
    follow: true,
  },
};

export const dynamic = "force-static";

function Section({ title, children }: any) {
  return (
    <section className="rounded-2xl border border-sky-950/40 bg-slate-950/70 p-8">
      <h2 className="text-xl font-semibold text-white">{title}</h2>
      <div className="mt-4 space-y-4 text-slate-300">{children}</div>
    </section>
  );
}

function Signal({ label, value }: any) {
  return (
    <div className="rounded-xl border border-sky-900/40 bg-slate-900/60 p-4">
      <div className="text-xs uppercase text-sky-300">{label}</div>
      <div className="mt-2 text-sm text-slate-200">{value}</div>
    </div>
  );
}

export default function HodgeConjectureAlgebraicityObstructionPage() {
  return (
    <main className="mx-auto w-full max-w-[1100px] px-6 py-14 space-y-12">

      {/* HERO */}
      <section className="rounded-3xl border border-sky-950/50 bg-slate-950/80 p-10">
        <div className="text-xs uppercase tracking-widest text-sky-300">
          Edge of Knowledge — Completeness Boundary
        </div>

        <h1 className="mt-4 text-4xl font-semibold text-white">
          The Hodge Conjecture
        </h1>

        <p className="mt-4 text-lg text-slate-300">
          Algebraicity is assumed complete. This assumption is unproven.
        </p>

        <div className="mt-8 grid gap-4 sm:grid-cols-3">
          <Signal label="Type" value="Completeness Boundary" />
          <Signal label="Assumption" value="Algebraic Exhaustiveness" />
          <Signal label="Failure" value="Unproven Closure" />
        </div>

        <div className="mt-8 border border-red-900/40 bg-red-950/20 p-4 text-sm text-red-200 rounded-xl">
          Non-actionable · Boundary only · No construction allowed
        </div>
      </section>

      {/* STATEMENT */}
      <Section title="Formal Statement">
        <p>
          Let X be a smooth projective complex variety. The Hodge Conjecture
          asserts that every rational (p,p)-class is algebraic.
        </p>
      </Section>

      {/* CORE */}
      <Section title="Core Boundary">
        <p>
          All known approaches assume that algebraic cycles generate the full
          space of rational Hodge classes.
        </p>

        <p className="text-red-300">
          This is a completeness claim—not a proven property.
        </p>
      </Section>

      {/* STRATEGY LIMIT */}
      <Section title="Strategy Limitation">
        <ul className="list-disc pl-6">
          <li>Cycle constructions are partial generators</li>
          <li>Analytic methods preserve type but not origin</li>
          <li>Reduction arguments depend on known cases</li>
          <li>Obstruction methods are incomplete</li>
        </ul>

        <p className="text-red-300">
          No approach spans the full space of possible Hodge classes.
        </p>
      </Section>

      {/* COMPLETENESS FAILURE */}
      <Section title="Completeness Failure Condition">
        <p>
          Let S = space of all rational (p,p)-classes.
        </p>

        <p>
          Let A = subspace generated by algebraic cycles.
        </p>

        <p className="text-red-300">
          The conjecture assumes: S = A
        </p>

        <p>
          This equality is not established.
        </p>
      </Section>

      {/* EXOTIC POSSIBILITY */}
      <Section title="Unresolved Possibility">
        <p>
          There may exist classes in S \ A:
        </p>

        <ul className="list-disc pl-6">
          <li>Analytic in origin</li>
          <li>Indistinguishable by current invariants</li>
          <li>Not representable by algebraic cycles</li>
        </ul>

        <p className="text-red-300">
          Their existence cannot be excluded.
        </p>
      </Section>

      {/* FALSIFICATION */}
      <Section title="Falsifiable Resolution Requirement">
        <ul className="list-disc pl-6">
          <li>Universal proof of S = A</li>
          <li>Explicit example where S ≠ A</li>
        </ul>

        <p>
          Any valid resolution must address completeness directly.
        </p>
      </Section>

      {/* CLAIM BOUNDARY */}
      <Section title="Claim Eligibility Boundary">
        <p>
          Any framework assuming algebraic exhaustiveness without proof exceeds
          its epistemic authority.
        </p>

        <p className="text-red-300">
          Partial generation does not imply completeness.
        </p>
      </Section>

      {/* FINAL */}
      <section className="border border-red-900/40 bg-red-950/20 p-8 rounded-2xl">
        <h2 className="text-xl font-semibold text-white">
          Boundary Judgment
        </h2>
        <p className="mt-4 text-red-200">
          The Hodge Conjecture is not blocked by lack of construction—it is
          blocked by an unproven completeness assumption. Any approach that does
          not resolve this boundary cannot claim full coverage.
        </p>
      </section>

      <div className="text-center text-sm text-slate-500">
        Canonical · Completeness-bound · Non-constructive · Versioned
      </div>
    </main>
  );
}
