import { ShadowInspector, InspectionFinding } from "../shadowInspectionService";
import { SnapshotDiff } from "../shadowSnapshotDiffService";
import { callModel } from "../model-router";

/*
  Assistive AI inspector:
  - advisory only
  - no authority
  - no code mutation
*/

export const RefactorSuggestionInspector: ShadowInspector = {
  name: "refactor-suggestion-inspector",

  async inspect(diff: SnapshotDiff): Promise<InspectionFinding[]> {
    const findings: InspectionFinding[] = [];

    const changedFiles = [
      ...diff.added,
      ...diff.modified,
    ].slice(0, 10); // cap scope for cost + safety

    if (changedFiles.length === 0) {
      return findings;
    }

    const prompt = `
You are a senior software engineer reviewing a code diff.

TASK:
- Suggest potential refactors or structural improvements.
- Do NOT propose stylistic nitpicks.
- Do NOT rewrite code.
- Focus on maintainability, separation of concerns, and clarity.
- Output a BULLET LIST of short suggestions.
- If nothing meaningful applies, say "No refactor suggestions."

FILES TO CONSIDER:
${changedFiles.join("\n")}
`;

    let response: string;

    try {
      response = await callModel("gpt-4.1-mini", prompt);
    } catch {
      return [
        {
          id: "refactor-inspector-failure",
          severity: "info",
          message:
            "Refactor suggestion inspector unavailable; no suggestions generated.",
        },
      ];
    }

    if (!response || response.toLowerCase().includes("no refactor")) {
      return findings;
    }

    findings.push({
      id: "refactor-suggestions",
      severity: "info",
      message: "Optional refactor suggestions generated by assistive AI.",
      filePaths: changedFiles,
    });

    findings.push({
      id: "refactor-suggestions-detail",
      severity: "info",
      message: response.trim(),
    });

    return findings;
  },
};
